### PR TITLE
define seperate timers for updates and logging

### LINKED ISSUE #45: readsensors update timing tied to logging packet send timing
autonomous functions may need sensor updates more frequently, which could cause sensor read duplication

### PR DESCRIPTION
**Pull request by robberwick**
Define seperate timers for all the various updates and
logging operations

Fixes #45

### CODE REVIEW

**Comment by markmellors** [comment]
initialises ok, drives fine

**Comment by markmellors** [comment]
image
time is now slower than 10Hz. is 0.14sec as expected?

**Comment by markmellors** [comment]
image
for comparison, this is what it looks like when the timer is set to 10ms

**Comment by robberwick** [comment]
well, I guess we know that the frequency we're setting is the _mininum_ delay between operations, so the logging one looks right.

**Pull request merged**
